### ISSUE TITLE
Verify Deadline

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/Terra-Official-Plugins#96]
The Terra plugin for Deadline is ready for prime time. We just need to verify and document how to install it. Then get this over to main.

**Comment by ddesmond** [comment]
We need to deterministicaly remove old deadline setup from all places (including images in registry) and make the new one as only option on all clusters.

**Comment by aldmbmtl** [comment]
This setup is almost perfect!

Aside from that launcher issue, the default install has authentication enabled. This broke Pluto from being able to mount and read deadline. To fix it I had to disable auth on the webservice. If we can by default disable this auth since it is isolated in the cluster, that would be a cool initial setup to have. Or we should add it to a doc.

This is the step I had to do to get it to work. 

https://docs.thinkboxsoftware.com/products/deadline/10.4/1_User%20Manual/manual/web-service.html#setup

**Comment by aldmbmtl** [comment]
Nodes are also failing to join the farm with the following error. I am assuming this is because of the above comment about the desktop file?

```
Creating default config file:/root/Thinkbox/Deadline10/deadline.ini
WARNING: Ignoring HOME environment because effective user is root.
service was not added to the CommandLineParser.
Is tracked by resource tracker: False
Scanning for auto configuration
Auto Configuration: No auto configuration for Repository Path could be detected, using local configuration
Connecting to repository
Could not connect to Deadline Repository: Could not retrieve NetworkRoot from "/var/lib/Thinkbox/Deadline10/deadline.ini" because it does not exist.

You may need to reinstall Deadline.
Deadline Worker will try to connect again in 10 seconds...
```

**Comment by aldmbmtl** [comment]
Got this working by passing in the deadline config to the workstation templates. This got them to boot and join with no issue. 

```yaml
apiVersion: junovfx.com/v1
kind: Workstation
metadata:
  name: artist
spec:
  registry: {{ .Values.registry }}
  icon: "https://cdn-icons-png.flaticon.com/512/1985/1985582.png"
  label: "Artist"
  group: "Production"
  repo: "polaris-workstation"
  cpu: "4"
  ram: "40Gi"
  tag: "unstable-ubuntu-22"
  mode: "interactive"
  deploy: "latest"
  env:
    - name: "foundry_LICENSE"
      value: "xxxx@x.x.x.x"
    - name: "DEADLINE_CONFIG_FILE"
      value: "/apps/deadline/client/deadline.ini"
    - name: "DEADLINE_PATH"
      value: "/apps/deadline/client/bin"
    - name: "DEADLINE_CUSTOM_PATH"
      value: "/apps/deadline/repository/custom/"
```

I actually really like this approach. It does make me think that Terra should be able to "push" environment vars that are required by the app that is installed. Kind of like the metadata can ship a special "env" key value that then Kuiper will go scrape the vars from and then auto populate on workstation launch.
